/**
 * Turn an entity template into a blank stub.
 *
 * The files in `.planning/_templates/` are *examples*, not blanks. They are
 * generated by `.test/update_schemas.py::save_example`, which fills every field
 * with a description of itself — `"appearance": "Physical description..."` —
 * and prepends an `_INSTRUCTION` key aimed at a model. That is right for
 * showing an AI the shape of an entity, and wrong for seeding a new one.
 *
 * Copying an example into the campaign verbatim produced a file where every
 * field looked written. Two consequences, both found by hand:
 *
 *   1. The sidebar listed the new NPC as "Example Character Name", because
 *      entities are labelled by their `name` field.
 *   2. `mergeGenerated` fills blanks and never replaces — correctly — so
 *      "Flesh out with AI" became a permanent no-op. Every generated field was
 *      discarded in favour of the description that happened to be sitting
 *      there, and the GM saw an NPC full of "Personality traits and demeanour…"
 *      that no amount of generating would fix.
 *
 * So the rule here is: an example's values are documentation, not data. Keep
 * the shape, keep what the GM typed, blank the rest.
 */

/** Answer ids the wizards collect, and the entity field each one belongs in.
 *
 *  The examples carry no `[Token]` placeholders, so substitution alone never
 *  reaches `name` — which is why stubs were anonymous. This map is the one
 *  place that knowledge lives; a field is only written when the template's own
 *  shape has somewhere to put it. */
const ANSWER_TO_FIELD: Record<string, string> = {
  Name: "name",
  Concept: "concept",
  Role: "role",
  Significance: "significance",
  Description: "gmSummary",
  Type: "type",
  Region: "region",
  // The Visual Anchor asks for "appearance to treat as absolute canon", which
  // is the appearance field in every sense -- so it is stored there rather
  // than beside it. Keeping both would mean asking the GM to understand two
  // overlapping description fields. The merge then protects it, which is what
  // "canon" has to mean; a GM who would rather the model invent the look
  // leaves the anchor blank and generation fills it.
  Visuals: "appearance",
};

/** The wizard asks for "NPC / Bestiary / PC"; the entity stores a `kind`.
 *
 *  Mirrors the stub endpoint in `api/routers/campaign.py`, which uses `kind` to
 *  decide the folder and which the loose-ends report uses to know that a
 *  bestiary template is exempt from placement by nature. The examples predate
 *  the field, so it is added rather than filled. */
const ENTITY_TYPE_TO_KIND: Record<string, string> = {
  NPC: "individual",
  Bestiary: "type",
  PC: "pc",
};

/** `[Key]` and `[Key Name]`, the convention the markdown templates use. */
function substituteTokens(text: string, variables: Record<string, string>): string {
  let out = text;
  for (const [key, value] of Object.entries(variables)) {
    if (!value) continue;
    out = out.replace(new RegExp(`\\[(${key}|${key} Name)\\]`, "gi"), value);
  }
  return out;
}

const same = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b);

/**
 * Keep whatever substitution changed; blank whatever is still the example.
 *
 * Comparing against the untouched example is exact — no guessing at which
 * strings look like prose — so a template that *does* use tokens keeps working
 * and one that doesn't comes out empty rather than pre-filled with its own
 * documentation.
 */
function blankUnchanged(example: unknown, filled: unknown): unknown {
  if (typeof filled === "string") return same(example, filled) ? "" : filled;

  if (Array.isArray(filled)) {
    // Example entries are illustrations ("Combat Reflexes [15] - Reacts
    // quickly (B43)"). An entry only survives if substitution rewrote it.
    const exampleArr = Array.isArray(example) ? example : [];
    return filled.filter((entry, i) => !same(exampleArr[i], entry));
  }

  if (filled && typeof filled === "object") {
    const exampleObj = (example && typeof example === "object" ? example : {}) as Record<string, unknown>;
    const out: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(filled as Record<string, unknown>)) {
      // `_INSTRUCTION` and friends are directions to a model, never campaign
      // data. One of them reached a real character file before this existed.
      if (key.startsWith("_")) continue;
      out[key] = blankUnchanged(exampleObj[key], value);
    }
    return out;
  }

  return filled;
}

/**
 * Instantiate `templateText` as a new entity.
 *
 * Non-JSON templates (the markdown episode overview) get token substitution and
 * nothing else — there is no shape to blank.
 */
export function instantiateTemplate(
  templateText: string,
  variables: Record<string, string>
): string {
  const substituted = substituteTokens(templateText, variables);

  let example: unknown;
  let filled: unknown;
  try {
    example = JSON.parse(templateText);
    filled = JSON.parse(substituted);
  } catch {
    return substituted;
  }
  if (!filled || typeof filled !== "object" || Array.isArray(filled)) return substituted;

  const blank = blankUnchanged(example, filled) as Record<string, unknown>;

  // The GM already answered these; a stub that drops them would ask twice.
  for (const [answerId, field] of Object.entries(ANSWER_TO_FIELD)) {
    const value = variables[answerId];
    if (!value || !value.trim()) continue;
    if (!(field in blank)) continue;
    blank[field] = value.trim();
  }
  // Story documents are titled, not named.
  if (!("name" in blank) && "title" in blank && variables.Name?.trim()) {
    blank.title = variables.Name.trim();
  }

  // Only the character wizard asks this, so only character stubs get a kind.
  const kind = ENTITY_TYPE_TO_KIND[(variables.EntityType || "").trim()];
  if (kind) {
    blank.kind = kind;
    // A template carries no narrative weight of its own, so it carries no
    // significance either — the same rule the generation path's postProcess
    // applies. The wizard's Significance field defaults to "core", which would
    // otherwise make every bestiary entry a core cast member.
    if (kind === "type" && "significance" in blank) blank.significance = "";
  }

  return JSON.stringify(blank, null, 2);
}
